server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-application
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**