server:
  port: 9090
spring:
  application:
    name: order-application
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  cloud:
    function:
      definition: startSaga;reserveCustomerBalanceStage;reserveProductStockStage
    stream:
      kafka:
        binder:
          brokers: localhost:29092
      bindings:
        startSaga-in-0:
          destination: outbox.event.PLACE_ORDER_REQUEST
        reserveCustomerBalanceStage-in-0:
          destination: outbox.event.RESERVE_CUSTOMER_BALANCE_RESPONSE
        reserveProductStockStage-in-0:
          destination: outbox.event.RESERVE_PRODUCT_STOCK_RESPONSE